### ISSUE TITLE
CFBundleIdentifier Error

### ISSUE THREAD

**Issue by botsbuzz** [insiderdev/minimal-quotes#39]
When I launch the app using yarn run:ios I receive the error:

`Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

Any idea?

Thank you for your great project,

Stefano

**Comment by gaykov** [comment]
Hello @botsbuzz!

Thank you so much for being interested in our project. Actually, it's a common problem with RN and XCode 10. Have you tried this solution: https://stackoverflow.com/a/41854111/9582178 ?

Please, let me know if it worked for you.
